runtime: java17  # or java11, depending on your Spring Boot app's compatibility
entrypoint: java -jar target/board-game-journal-0.0.1-SNAPSHOT.jar  # Make sure this points to your JAR file

instance_class: F1  # Specify F1 instance class for free tier usage

automatic_scaling:
  target_cpu_utilization: 0.65  # Use moderate CPU utilization for efficient scaling
  min_instances: 0  # Set to 0 to use free-tier and avoid charges when idle
  max_instances: 1  # Limit to 1 instance to stay within free-tier usage
  max_idle_instances: 1  # Allow only 1 idle instance to reduce costs
  max_pending_latency: 30s  # Allows for a slight delay before scaling to avoid creating new instances too quickly
  min_idle_instances: 0  # No idle instances when not in use
