name: Build Spring Boot Project

on:
  push:  # Trigger on push events
    branches:
      - '**'  # This triggers for commits to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
