name: Deploy to Google App Engine

# Trigger this workflow on push events
on:
  push:
    branches:
      - '**'  # This triggers for commits to any branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (ensure correct version)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Your GCP Service Account Key (JSON format)

      # Step 5: Set up Google Cloud SDK (gcloud CLI)
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Your GCP project ID
          export_default_credentials: true

      # Step 6: Build and package with Maven
      - name: Build and package with Maven
        run: ./mvnw clean package -DskipTests

      # Step 7: Deploy to Google App Engine
      - name: Deploy to Google App Engine
        run: ./mvnw appengine:deploy
